# Generated by Django 3.0.8 on 2020-08-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exam_timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
                ('exam_type', models.CharField(max_length=50)),
                ('invigilator', models.CharField(max_length=50)),
                ('roomno', models.IntegerField(max_length=10)),
            ],
        ),
    ]
