# Generated by Django 3.0.8 on 2020-10-03 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='constraints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('exam_date', models.DateField()),
                ('exam_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('fname', models.CharField(default='none', max_length=50, primary_key=True, serialize=False)),
                ('faculty_id', models.IntegerField()),
                ('faculty_status', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='y', max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('dept', models.CharField(choices=[('it', 'information technology'), ('eee', 'electrical'), ('cse', 'computer science'), ('ece', 'electronics and communication')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noofexams', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('roomno', models.IntegerField(primary_key=True, serialize=False)),
                ('roomcapacity', models.IntegerField()),
                ('room_status', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('rollno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_dept', models.CharField(choices=[('it', 'information technology'), ('eee', 'electrical'), ('cse', 'computer science'), ('ece', 'electronics and communication')], max_length=3)),
                ('year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
            ],
        ),
        migrations.CreateModel(
            name='tt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cse', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='conduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1-1', '1-1'), ('1-2', '1-2'), ('2-1', '2-1'), ('2-2', '2-2'), ('2-1', '2-1'), ('2-2', '2-2'), ('3-1', '3-1'), ('4-2', '4-2')], max_length=10)),
                ('dept', models.CharField(choices=[('it', 'information technology'), ('eee', 'electrical'), ('cse', 'computer science'), ('ece', 'electronics and communication')], max_length=3)),
                ('subject', models.CharField(default='none', max_length=50)),
                ('ex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.exam')),
                ('fna1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.faculty')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.room')),
            ],
        ),
    ]
