# Generated by Django 3.0.8 on 2020-09-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='examinvigilator_duties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('roomno', models.IntegerField()),
                ('invigilator', models.CharField(max_length=50)),
                ('exam_time', models.CharField(max_length=50)),
                ('exam_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='exam_timetable',
        ),
    ]
