# Generated by Django 3.0.8 on 2020-10-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conduct',
            name='fna2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
