# Generated by Django 3.0.8 on 2020-10-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_conduct_fna2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='number',
        ),
        migrations.RenameField(
            model_name='tt',
            old_name='cse',
            new_name='branch',
        ),
        migrations.AddField(
            model_name='tt',
            name='bname',
            field=models.CharField(max_length=50, null='False'),
            preserve_default='False',
        ),
    ]
