# Generated by Django 3.0.8 on 2020-09-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200901_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examinvigilator_duties',
            old_name='invigilator',
            new_name='faculty_name',
        ),
        migrations.AddField(
            model_name='examinvigilator_duties',
            name='faculty_id',
            field=models.IntegerField(null=True),
        ),
    ]
