# Generated by Django 3.0.8 on 2020-09-01 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20200901_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='examinvigilator_duties',
        ),
    ]
