# Generated by Django 3.0.8 on 2020-10-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20201017_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='tt',
            name='btt',
            field=models.ImageField(default='null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='tt',
            name='branch',
            field=models.CharField(default='null', max_length=5),
        ),
    ]
