# Generated by Django 3.0.8 on 2020-09-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20200907_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='semester',
            field=models.CharField(choices=[('1-1', '1-1'), ('1-2', '1-2'), ('2-1', '2-1'), ('2-2', '2-2'), ('2-1', '2-1'), ('2-2', '2-2'), ('3-1', '3-1'), ('4-2', '4-2')], max_length=10),
        ),
    ]
