# Generated by Django 3.0.8 on 2020-09-08 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20200907_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.faculty'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='faculty_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='roomno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.room'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
