# Generated by Django 3.0.8 on 2021-01-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20210107_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tt',
            name='Branch',
            field=models.CharField(choices=[('it', 'IT'), ('eee', 'EEE'), ('cse', 'CSE'), ('ece', 'ECE')], default='CSE', max_length=5),
        ),
    ]
