# Generated by Django 3.0.8 on 2021-01-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20210107_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tt',
            name='Branch',
            field=models.CharField(choices=[('cse', 'CSE'), ('it', 'IT'), ('eee', 'EEE'), ('ece', 'ECE')], max_length=5),
        ),
    ]
