# Generated by Django 3.0.8 on 2020-09-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20200917_1805'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='exams',
            new_name='number',
        ),
    ]
