# Generated by Django 3.0.8 on 2020-09-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20200917_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='constraints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cdate', models.DateField()),
            ],
        ),
    ]
