# Generated by Django 3.0.8 on 2020-09-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='tt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cse', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_status',
            field=models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='y', max_length=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='y', max_length=1),
        ),
    ]
